### ISSUE TITLE
How do you open the decrypted.smime file

### ISSUE THREAD

**Issue by kps143** [AF-VCD/Mrs-SMIME#2]
sorry if this should be obvious, but I can't seem to open the decrypted.smime file.  Could you provide instructions?

**Comment by ckhordiasma** [comment]
Hey sorry I'm replying to this so late. There is now some more detailed instructions on the main page, but for your specific question:

the decrypted.smime file isn't intended to be read directly. The script should produce additional files in the same folder as the decrypted.smime file.

**Comment by bwhung** [comment]
Thanks for this. Unfortunately, after selecting the smime.p7m file and the folder location to save the decrypted file, I am prompted to enter my PIN via MAC, but then I get the error "Failed to decrypt or decode file." I believe I have all the certificates on this machine as I am able to view all other webmail here. Any ideas of what I could be doing wrong? Thanks!

**Comment by ckhordiasma** [comment]
Are there any other error messages you get?

Does a decrypted.smime file get generated?

**Comment by bwhung** [comment]
This is what I see (below). And yes, the decrypted.smime file gets generated, but it is Zero bytes and empty when I open it with a text editor.

Prompting user for p7m file...
/Volumes/PATH/smime.p7m
Prompting user for output folder...
/Volumes/PATH/
Decrypting and decoding file ...
base64: invalid option -- d
Usage:	base64 [-hvD] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -D, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
Failed to decrypt or decode file
(base) Name-Air:Mrs-SMIME Name$

**Comment by ckhordiasma** [comment]
ok thanks, the error stuff you posted narrowed down the issue for me, I think. Try redownloading the script (I just updated it) and try again to see if it works.

**Comment by GuilesHomer** [comment]
Howdy. I wasn't prompted for PIN and received the following error. Thoughts?

Decrypting and decoding file ...
security: failed to add data to decoder: UNKNOWN (-8147(d)
security: problem decoding
Failed to decrypt or decode file

**Comment by ckhordiasma** [comment]
closed for inactivity
