### ISSUE TITLE
Not prompted for PIN

### ISSUE THREAD

**Issue by GuilesHomer** [AF-VCD/Mrs-SMIME#3]
Howdy. I wasn't prompted for PIN and received the following error. Thoughts?

Decrypting and decoding file ...
security: failed to add data to decoder: UNKNOWN (-8147(d)
security: problem decoding
Failed to decrypt or decode file

**Comment by ckhordiasma** [comment]
What kind of Mac and operating system do you have?

**Comment by GuilesHomer** [comment]
![Screen Shot 2021-04-24 at 5 56 59 PM](https://user-images.githubusercontent.com/83132695/115974989-9e69b480-a526-11eb-9d22-f76c1c08bb7b.png)

**Comment by ckhordiasma** [comment]
sorry for the delay. Some follow-up questions:

Do you have multiple smart card readers on your computer? 

Do you have Activclient installed on your mac?

Can you try downloading a different p7m file and trying ?

**Comment by ckhordiasma** [comment]
Also: try downloading the script files and trying again, I just made some fixes. I don't think the fixes were relevant to your issue but you never know.

**Comment by ckhordiasma** [comment]
closed for inactivity
