### ISSUE TITLE
Trouble running 'bash mrs-smime'

### ISSUE THREAD

**Issue by krboar** [AF-VCD/Mrs-SMIME#5]
Hello, I'm getting the following issue when trying to run 'bash-smime':

mrs-smime.sh: line 7: syntax error near unexpected token newline'
mrs-smime.sh: line 7: `!DOCTYPE html'

I checked line 7 of the code but I didn't seem to find anything wrong. Am I missing something here?

**Comment by ckhordiasma** [comment]
I think you downloaded the file incorrectly, can you describe how you downloaded the file?

**Comment by krboar** [comment]
Yup. You're right. I "saved link as" instead of downloading the .zip file. Thanks!

**Comment by ckhordiasma** [comment]
np! also note that I found it's a little harder to download the smime.p7m file now. See https://github.com/AF-VCD/Mrs-SMIME/issues/4#issuecomment-881465848
